#!/usr/bin/env Rscript
# rmParentalMissing
# Remove sites that have many missing calls in either parental population for Ancestry HMM
# M. Wilson Brown
# June 9, 2024
#
# 
# arg[1] is the missing frequency file for sites in one parental population generated by PLINK2
# arg[2] is the missing frequency file for sites in the other parental population generated by PLINK2
# arg[3] is the cutoff for missingness 
args = commandArgs(trailingOnly=TRUE)

# load variant missingness for parental samples
p1_miss <- read.csv(as.character(arg[1]), sep = "\t", header = T)
p2_miss <- read.csv(as.character(arg[2]), sep = "\t", header = T)

# ### Plots
# ggplot() +
#   geom_freqpoly(data = p1_miss, aes(x=F_MISS, color=X.CHROM))
# 
# ggplot() +
#   geom_freqpoly(data = p2_miss, aes(x=F_MISS, color=X.CHROM))

## too many missing
# p1_miss_high <- p1_miss[which(p1_miss$F_MISS > as.numeric(arg[3])),]
# 
# p2_miss_high <- p2_miss[which(p2_miss$F_MISS > as.numeric(arg[3])),]

#combine parental population missing frequencies
f_miss <- left_join(p1_miss, p2_miss, join_by("X.CHROM", "POS"))

# remove sites that have too many missing in either parental population
keep <- f_miss[which(f_miss$F_MISS.x < as.numeric(arg[3]) & f_miss$F_MISS.y < as.numeric(arg[3])),]

# write those sites to file
write.table(keep[1:2], "keep_filt_sites.txt", 
            sep = "\t", col.names = F, row.names = F, quote = F)
